version: "3.9"
services:
  mongo:
    container_name: to_do_mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
  frontend:
    container_name: to_do_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: to_do_web
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    container_name: to_do_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: to_do_server
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - DB_HOST=localhost
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
